// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/manga.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Data structure representing a manga update
type MangaUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Chapter       string                 `protobuf:"bytes,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaUpdate) Reset() {
	*x = MangaUpdate{}
	mi := &file_proto_manga_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaUpdate) ProtoMessage() {}

func (x *MangaUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaUpdate.ProtoReflect.Descriptor instead.
func (*MangaUpdate) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{0}
}

func (x *MangaUpdate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MangaUpdate) GetChapter() string {
	if x != nil {
		return x.Chapter
	}
	return ""
}

func (x *MangaUpdate) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Response message from the Notifier
type NotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationResponse) Reset() {
	*x = NotificationResponse{}
	mi := &file_proto_manga_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationResponse) ProtoMessage() {}

func (x *NotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_manga_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationResponse.ProtoReflect.Descriptor instead.
func (*NotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_manga_proto_rawDescGZIP(), []int{1}
}

func (x *NotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *NotificationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_manga_proto protoreflect.FileDescriptor

const file_proto_manga_proto_rawDesc = "" +
	"\n" +
	"\x11proto/manga.proto\x12\x05proto\"O\n" +
	"\vMangaUpdate\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\achapter\x18\x02 \x01(\tR\achapter\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"J\n" +
	"\x14NotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2O\n" +
	"\bNotifier\x12C\n" +
	"\x10SendNotification\x12\x12.proto.MangaUpdate\x1a\x1b.proto.NotificationResponseB*Z(github.com/KioskDetonator/AniScale/protob\x06proto3"

var (
	file_proto_manga_proto_rawDescOnce sync.Once
	file_proto_manga_proto_rawDescData []byte
)

func file_proto_manga_proto_rawDescGZIP() []byte {
	file_proto_manga_proto_rawDescOnce.Do(func() {
		file_proto_manga_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_manga_proto_rawDesc), len(file_proto_manga_proto_rawDesc)))
	})
	return file_proto_manga_proto_rawDescData
}

var file_proto_manga_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_manga_proto_goTypes = []any{
	(*MangaUpdate)(nil),          // 0: proto.MangaUpdate
	(*NotificationResponse)(nil), // 1: proto.NotificationResponse
}
var file_proto_manga_proto_depIdxs = []int32{
	0, // 0: proto.Notifier.SendNotification:input_type -> proto.MangaUpdate
	1, // 1: proto.Notifier.SendNotification:output_type -> proto.NotificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_manga_proto_init() }
func file_proto_manga_proto_init() {
	if File_proto_manga_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_manga_proto_rawDesc), len(file_proto_manga_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_manga_proto_goTypes,
		DependencyIndexes: file_proto_manga_proto_depIdxs,
		MessageInfos:      file_proto_manga_proto_msgTypes,
	}.Build()
	File_proto_manga_proto = out.File
	file_proto_manga_proto_goTypes = nil
	file_proto_manga_proto_depIdxs = nil
}
